### ISSUE TITLE
Duplicate loading when cache_classes=false and eager_load=true

### ISSUE THREAD

**Issue by bencrouse** [parndt/decorators#12]
For a variety of reasons I won't go into here, I have to run my app with `eager_load = true` in development (where `cache_classes = false`). (I realize this is an unusual Rails setup for development env).

I'm trying to use this gem to handle decoration loading, but in this situation, the decorator is loaded twice on application initialization, once when the code is eager loaded (because Rails eager loads `app/**/*`) and once when this gem runs its `load!` method.

I tried various fixes changing when/where `Decorators.load!` is run, but no luck. I was wondering if someone with a deeper understanding of the Rails autoloading and boot processes had any thoughts.

**Comment by parndt** [comment]
Oh dear..  [here's the guts of it](https://github.com/parndt/decorators/blob/master/lib/decorators/railtie.rb#L6-L14)

So currently the library says that if you're eager loading then we have to use `after_initialize`, otherwise we use `to_prepare`.
Then, if you're caching classes it [says](https://github.com/parndt/decorators/blob/master/lib/decorators.rb#L6-L14) to use `require`, otherwise to use `load`.

I think to cater to this situation the plugin might have to store away which things it's already decorated in that wave of decorations and skip decorators that it's already done.  We could do this [in the register step](https://github.com/parndt/decorators/blob/master/lib/decorators/paths.rb#L11-L13) by appending to an instance variable like `@registered_but_not_applied` and then removing from this variable each time we loaded or required a decorator.  As development mode is where most of the pain comes from, due to code reloading, I think that this would have the caveat that you'd have to refresh the `@registered_but_not_applied` collection to match the `@registered` collection at the start of each Rails request in development mode so that it knows to do it again.

Hopefully this all makes a certain amount of sense.. do you have any suggestions for what might work?

**Comment by bencrouse** [comment]
I follow your logic, but I'm not sure that would address the problem.... the reason it wouldn't work is because the first "round" of the decorators getting loaded is [during the `:eager_load!` initializer] (https://github.com/rails/rails/blob/master/railties/lib/rails/application/finisher.rb#L53) which [uses `require` to load the files](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/dependencies/autoload.rb#L70).

Since it's using `require`, Rails autoload won't work with those files. (I believe it needs to use `require_dependency` to work with autoload?)

I tried running `Decorators.load!` in `config.before_eager_load`, which I really thought would work, but didn't for reasons I can't explain. Under this setup, changing the file even once caused the decorations to disappear on the next request. Maybe doing a hard `require` on a file even once results in it not working with Rails autoloading?

**Comment by bencrouse** [comment]
Actually this gave me an idea to try monkey-patching `ActiveSupport::Autoload#eager_load!` to use require_dependency. FML IM A TERRIBLE PERSON. I'll report back if that works.

**Comment by parndt** [comment]
OK, if we need to use require_dependency maybe that'd work better?

**Comment by bencrouse** [comment]
sorry, i tried to reproduce in a fresh rails app and couldn't. my quest continues. thanks for your time, i think this gem is nice.

**Comment by parndt** [comment]
Thank you!!
